import React, {useEffect, useRef, useState} from 'react';
import './landing.css';
import {startForestCursor, startForestScroll} from './landingEffects';

const landingOnly = __FORESTGUARD_LANDING_ONLY__;

export function ForestLogo({size=42}) {
  return <svg className="forest-logo" width={size} height={size} viewBox="0 0 100 112" fill="none" role="img" aria-label="Forest Guard: tree and leaf inside a protective shield">
    <path d="M73 19C63 16 54 12 46 7 33 15 20 20 9 22V52C9 76 21 91 40 103" stroke="var(--logo-ink, #193b29)" strokeWidth="5.5" strokeLinejoin="round"/>
    <path d="m46 20-15 22 9-2-18 21 13-2-21 22 22-3-16 15h16c8-17 21-20 35-25L55 57l11 2-17-19 10 2Z" fill="var(--logo-ink, #193b29)"/>
    <path d="m80 22 13 5v24c0 11-1 20-5 28" stroke="#d1aa22" strokeWidth="4.5" strokeLinejoin="round"/>
    <circle cx="77" cy="21" r="4.5" stroke="#d1aa22" strokeWidth="3.5"/>
    <circle cx="88" cy="82" r="4.5" stroke="#d1aa22" strokeWidth="3.5"/>
    <path d="M40 108c2-18 8-32 24-37 10-3 17-6 21-13-1 24-9 43-26 46-8 1-14 0-19 4Z" fill="#718b20"/>
    <path d="M40 108c8-16 17-25 31-33-13 12-22 22-31 33Z" fill="var(--logo-cutout, #fff)"/>
  </svg>;
}

function ForestAnimation({stage,paused,onPause}){
  return <div className={`forest-animation stage-${stage} ${paused?'paused':''}`}>
    <div className="motion-heading"><span>FOREST INTELLIGENCE IN MOTION</span><button onClick={onPause} aria-label={paused?'Play forest animation':'Pause forest animation'}>{paused?'Play':'Pause'}</button></div>
    <div className="observation-window"><div className="window-chrome"><span className="window-dots"><i/><i/><i/></span> Satellite image <span className="window-lock">◈</span></div>
      <div className="scene-heading"><strong>Forest landscape</strong><span>Workflow illustration</span></div>
      <svg className={`forest-scene stage-${stage}`} viewBox="0 0 430 240" role="img" aria-label="Animated forest landscape with satellite scanning and vegetation layers">
        <defs><linearGradient id="terrain" x2="1" y2="1"><stop stopColor="#183b29"/><stop offset="1" stopColor="#0a201c"/></linearGradient><linearGradient id="scan" x2="0" y2="1"><stop stopColor="#bcf4a0" stopOpacity="0"/><stop offset="1" stopColor="#bcf4a0" stopOpacity=".6"/></linearGradient><pattern id="scenegrid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#86b58b" strokeWidth=".5" opacity=".22"/></pattern><g id="pine"><path d="m0-13-8 12h4l-8 11h24L4-1h4L0-13Z" fill="#77b176"/><path d="M0 8v8" stroke="#a2c99a" strokeWidth="2"/></g></defs>
        <rect width="430" height="240" rx="8" fill="url(#terrain)"/>
        <path d="M-10 75C45 35 102 140 161 101S258 12 320 46s98 16 131-10" fill="none" stroke="#305443" strokeWidth="54"/>
        <path d="M-10 75C45 35 102 140 161 101S258 12 320 46s98 16 131-10" fill="none" stroke="#68a9a0" strokeOpacity=".52" strokeWidth="15"/>
        <rect width="430" height="240" fill="url(#scenegrid)"/>
        {[[44,145],[80,180],[120,151],[162,199],[196,165],[243,199],[281,155],[326,181],[369,143],[399,197],[40,29],[110,31],[176,41],[225,27],[326,108],[374,81]].map(([x,y],i)=><use key={i} href="#pine" x={x} y={y} opacity={.55+(i%3)*.15}/>)}
        <path className="study-polygon" d="m93 51 133-24 108 80-51 109-137-21-69-81Z" fill={stage===1?'#91df6730':'#91df6708'} stroke="#d5e793" strokeWidth="1.8" strokeDasharray="6 4"/>
        <path className="change-patch" d="m255 131 37-15 21 24-15 36-34-12Z" fill={stage===2?'#e0bc6466':'transparent'} stroke={stage===2?'#e0bc64':'transparent'}/>
        <rect className="satellite-scan" x="0" y="0" width="430" height="55" fill="url(#scan)"/>
        <g className="satellite-icon" transform="translate(350 30)"><path d="m0 0 9 9-9 9-9-9Z" fill="#c1d8be"/><path d="m-24-8 10 10-10 10-10-10Zm46 20 10 10-10 10-10-10Z" fill="#8ba8a1" stroke="#b6d4b5"/><path d="m-14 2 7 5m14 6 9 5" stroke="#c1d8be" strokeWidth="2"/></g>
        <text x="15" y="222" fill="#c4d7c0" fontSize="9" fontFamily="monospace">43QFE · 10 m GRID</text><circle className="scene-pulse" cx="229" cy="128" r="5" fill="#c9eca3"/><circle className="scene-ring" cx="229" cy="128" r="18" fill="none" stroke="#c9eca3"/>
      </svg>
      <div className="scene-bottom"><ForestLogo size={26}/><div><strong>ForestGuard AI</strong><span>{['Read saved satellite observations','Mask clouds and uncertain pixels','Compare common usable coverage'][stage]}</span></div><i className="live-orb"/></div>
    </div>
    <div className="flow-connector"><i className="flow-pulse" aria-hidden="true"/><span><small>DATA FLOW</small>{['Satellite observation captured','Clouds and gaps filtered','Dates compared on one grid'][stage]}</span></div>
    <div className="analysis-window"><div className="analysis-icon">✦</div><div><strong>{['A view from above.','A clearer signal.','Evidence to review.'][stage]}</strong><span>{['Visible colours and leaf-growth signals','Usable pixels, consistent geographic grid','Inspect dates and vegetation indicators'][stage]}</span></div><div className="analysis-bars"><i/><i/><i/><i/><i/></div></div>
    <div className="motion-stages" aria-label="Satellite analysis stages"><div className="stage-rail"><i style={{width:`${stage*50}%`}}/><b key={stage} style={{left:`${stage*50}%`}}/></div>{['Observe','Prepare','Compare'].map((text,i)=><div className={`${i===stage?'active':''} ${i<stage?'complete':''}`} key={text}><i>{i<stage?'✓':`0${i+1}`}</i><span>{text}</span></div>)}</div>
    <p className="motion-caption">Satellite imagery → usable observations → local insights</p>
  </div>;
}

export default function Landing({onLogin}){
  const [stage,setStage]=useState(0),[paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches),[loginOpen,setLoginOpen]=useState(false),[password,setPassword]=useState(landingOnly?'':'joga@123'),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const dialog=useRef(null),cursor=useRef(null),workflow=useRef(null),workflowSteps=useRef([]);
  const [activeWorkflowStep,setActiveWorkflowStep]=useState(null);
  useEffect(()=>startForestScroll(),[]);
  useEffect(()=>startForestCursor(cursor.current),[]);
  useEffect(()=>{if(paused)return;const id=setInterval(()=>setStage(s=>(s+1)%3),3000);return()=>clearInterval(id);},[paused]);
  useEffect(()=>{let frame;const update=()=>{if(!workflow.current||!workflowSteps.current.length)return;const bounds=workflow.current.getBoundingClientRect(),centers=workflowSteps.current.map(node=>{const r=node.getBoundingClientRect();return r.top+r.height/2;});const start=centers[0]-bounds.top,end=centers.at(-1)-bounds.top,progress=Math.max(0,Math.min(1,(innerHeight*.8-bounds.top)/Math.max(1,bounds.height*.75))),orbit=workflowSteps.current[0].querySelector('.workflow-orbit').getBoundingClientRect();workflow.current.style.setProperty('--flow-start',`${start}px`);workflow.current.style.setProperty('--flow-end',`${end}px`);workflow.current.style.setProperty('--flow-progress',`${start+(end-start)*progress}px`);workflow.current.style.setProperty('--flow-x',`${orbit.left+orbit.width/2-bounds.left}px`);let nearest=0,distance=Infinity;centers.forEach((center,i)=>{const next=Math.abs(center-innerHeight/2);if(next<distance){nearest=i;distance=next;}});setActiveWorkflowStep(distance<innerHeight*.32?nearest:null);};const schedule=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update);};schedule();addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);return()=>{cancelAnimationFrame(frame);removeEventListener('scroll',schedule);removeEventListener('resize',schedule);};},[]);
  useEffect(()=>{if(loginOpen){dialog.current.showModal();dialog.current.scrollTop=0;}else dialog.current?.close();},[loginOpen]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.landing .reveal').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);
  function openLogin(){setError('');setLoginOpen(true);}
  async function signIn(event){event.preventDefault();if(landingOnly){setError('Officer sign-in is available in the local workspace.');return;}setBusy(true);setError('');try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({district:'Harda',beat:'Joga',password})});let result;try{result=await response.json();}catch{throw Error('This deployment does not have the ForestGuard sign-in service. Use the locally running workspace.');}if(!response.ok)throw Error(result.detail||'Could not sign in');setLoginOpen(false);onLogin(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="landing" id="home"><div ref={cursor} className="motion-cursor site-cursor" aria-hidden="true"><div className="site-cursor-pill"/></div><a className="skip-link" href="#landing-main">Skip to content</a>
    <header className="landing-nav"><a href="#home" className="landing-brand"><ForestLogo/><span>ForestGuard<small>Intelligence for a greener tomorrow</small></span></a><nav aria-label="Landing navigation"><a href="#about">About</a><a href="#workflow">How it works</a><a href="#access">Officer access</a><a href="#faq">FAQ</a></nav><button className="land-button" onClick={openLogin}>Officer login <span>↗</span></button></header>
    <main id="landing-main" className="landing-main"><section className="landing-hero"><div className="hero-copy"><div className="hero-intro">Our forests. Our future. Our responsibility.</div><p className="hero-aside">A clearer view from above. A better decision on the ground.</p><h1>Keep it <span key={stage} className="cycling-word">{['Green.','Protected.','Thriving.'][stage]}</span><br/><span className="lime-line">See the change.</span><br/><span className="mint-line">Guard the future.</span></h1><p className="hero-description">Turn satellite observations into a clearer picture of your forest. Explore the landscape, compare dates, and bring the evidence back to the officers who know it best.</p><div className="hero-actions"><button className="land-button" onClick={openLogin}>Explore your forest <span>↗</span></button><a className="land-button outline" href="#workflow">See how it works <span>↓</span></a></div><div className="hero-tags"><span><i/> Monitoring forests everywhere</span><span>Built for local operation</span></div></div><ForestAnimation stage={stage} paused={paused} onPause={()=>setPaused(!paused)}/></section>
    <section id="about" className="landing-section reveal"><div className="section-eyebrow">WHY FORESTGUARD?</div><h2>Every forest has a story.<br/><span>See what the landscape is telling you.</span></h2><p className="section-description">Bring observations, dates and geographic context together. Less time searching through files. More time understanding what needs a closer look.</p><div className="feature-grid">{[['01','Observe your landscape','Inspect saved satellite images, see when they were collected, and check how much of the landscape could be observed.','◈'],['02','Compare the evidence','Put two aligned observations side by side. Pan and zoom together, inspect common coverage and calculate vegetation indicators.','⌁'],['03','Keep the work with you','Maps, checks and reports stay on your computer. Open saved observations without an online basemap or paid model service.','♧']].map(([n,title,text,icon])=><article key={n}><div className="feature-number">{n}<span>{icon}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="workflow" className="landing-section workflow-section reveal"><div className="section-eyebrow">HOW FORESTGUARD WORKS</div><h2>Observe. Understand. <span>Act.</span></h2><p className="section-description">A traceable path from a satellite observation to a report you can review.</p><div className="workflow-track" ref={workflow} aria-label="How ForestGuard works, step by step"><span className="workflow-flow-line" aria-hidden="true"/><span className="workflow-flow-drop" aria-hidden="true"/>{[['Access your beat','Sign in and select your authorized district and forest area to open its saved observations.'],['Inspect the observation','View true-colour imagery with acquisition dates, collection dates and map location.'],['Check the signal','Run stored-data integrity checks and check a simple leaf-greenness indicator from satellite images.'],['Compare the dates','Explore aligned observations and their common usable coverage. Review visual differences in context.'],['Take the evidence','Download CSV or HTML reports with dates, coverage and provenance for further review.']].map(([title,text],i)=><article ref={node=>workflowSteps.current[i]=node} className={activeWorkflowStep===i?'is-focused':''} key={title}><div className="workflow-orbit"><span>STAGE</span><strong>0{i+1}</strong></div><div className="workflow-copy"><small>STEP 0{i+1}</small><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="workflow-result"><span>THE RESULT</span> Better observations. More informed forest decisions. <button onClick={openLogin}>Open the workspace ↗</button></div></section>
    <section id="access" className="landing-section access-section reveal"><div><div className="section-eyebrow">MONITOR YOUR FOREST</div><h2>Your forest.<br/><span>Your workspace.</span></h2><p className="section-description">A local workspace for officers monitoring forests across regions. Sign in to view your assigned forest area.</p><button className="land-button" onClick={openLogin}>Login to officer workspace <span>↗</span></button></div><div className="access-card"><ForestLogo size={65}/><div className="access-label">OFFICER WORKSPACE</div><h3>Your forest area</h3><p>Your district · Your forest</p><dl><dt>Satellite images</dt><dd>Copernicus satellite programme</dd><dt>Saved observations</dt><dd>Saved monthly and seasonal observations</dd><dt>Workspace</dt><dd><i/> Local & ready</dd></dl><button className="land-button outline" onClick={openLogin}>Enter workspace →</button></div></section>
    <section id="faq" className="landing-section faq-section reveal"><div><div className="section-eyebrow">COMMON QUESTIONS</div><h2>Got a question?</h2><p className="section-description">Common questions about ForestGuard.</p></div><div className="faq-items">{[['What can I do in the workspace?','Open saved satellite images, review monthly forest and fire reports, and download results.'],['Does it work without the Internet?','The application, maps and saved-data analysis run on this computer. Internet is needed only when acquiring fresh imagery or installing dependencies.'],['What does the vegetation indicator show?','The indicator compares visible and infrared light reflected by the land. Crops and scrub can also look green; it does not tell you which trees are legally protected.'],['Can ForestGuard monitor my forest?','Sign in and select an area available to your officer account. Map availability depends on saved imagery and a verified study boundary.'],['How should generated results be read?','The hero is an illustration. Generated forest classes and monthly history are simulated and are not measured results. Satellite images that have been acquired are shown with their collection dates.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="landing-final reveal"><ForestLogo size={48}/><h2>See more. <span>Protect better.</span></h2><p>Start with the evidence. Bring your forest into focus.</p><button className="land-button" onClick={openLogin}>Explore ForestGuard AI ↗</button></section>
    </main><footer className="landing-footer"><div><a href="#home" className="landing-brand"><ForestLogo size={36}/><span>ForestGuard<small>Intelligence for a greener tomorrow</small></span></a><p>Observe the landscape.<br/>Guard what matters.</p></div><div><strong>EXPLORE</strong><a href="#about">About ForestGuard</a><a href="#workflow">How it works</a></div><div><strong>FOREST AREAS</strong><a href="#access">Your assigned area</a><button onClick={openLogin}>Officer login</button></div><div><strong>THE PROJECT</strong><p>Local forest observation workspace<br/>© 2026 ForestGuard AI</p><a href="#faq">Questions & data context</a></div></footer>
    <dialog ref={dialog} className="officer-dialog" onCancel={()=>setLoginOpen(false)}><button className="dialog-close" aria-label="Close login" onClick={()=>setLoginOpen(false)}>×</button><ForestLogo size={50}/><div className="section-eyebrow">FOREST OFFICER WORKSPACE</div><h2>{landingOnly?'Officer access':'Welcome back.'}</h2><p>{landingOnly?'This public site presents ForestGuard. Officer sign-in is available in the locally running workspace.':'Your landscape, ready to explore.'}</p>{landingOnly?<button className="land-button" onClick={()=>setLoginOpen(false)}>Back to ForestGuard <span>→</span></button>:<><form onSubmit={signIn}><label>District<select aria-label="District" defaultValue="Harda"><option>Harda</option></select></label><label>Forest beat<select aria-label="Forest beat" defaultValue="Joga"><option>Joga</option></select></label><label>Password<div className="password-field"><input aria-label="Password" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?'Hide':'Show'}</button></div></label><small className="login-hint">District: Harda · Forest area: Joga</small>{error&&<p role="alert" className="login-error">{error}</p>}<button className="land-button" disabled={busy} type="submit">{busy?'Opening your workspace…':'Open officer workspace'} <span>→</span></button></form><span className="login-footnote">Harda district · Joga beat · Local session</span></>}</dialog>
  </div>;
}
