import React, {useEffect, useRef, useState} from 'react';
import './landing.css';

export function ForestLogo({size=42}) {
  return <svg width={size} height={size} viewBox="0 0 48 52" fill="none" aria-label="ForestGuard trees and shield"><path d="M24 3 43 11v14c0 12-10 20-19 24C15 45 5 37 5 25V11L24 3Z" stroke="currentColor" strokeWidth="3"/><path d="m24 12-8 12h5l-7 10h20l-7-10h5L24 12Z" fill="currentColor"/><path d="M24 33v7M13 23l-4 7h8m18-7 4 7h-8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></svg>;
}

function ForestAnimation({stage,paused,onPause}){
  return <div className={`forest-animation ${paused?'paused':''}`}>
    <div className="motion-heading"><span>FOREST INTELLIGENCE IN MOTION</span><button onClick={onPause} aria-label={paused?'Play forest animation':'Pause forest animation'}>{paused?'Play':'Pause'}</button></div>
    <div className="observation-window"><div className="window-chrome"><span className="window-dots"><i/><i/><i/></span> Sentinel-2 observation <span className="window-lock">◈</span></div>
      <div className="scene-heading"><strong>Joga research landscape</strong><span>Workflow illustration</span></div>
      <svg className={`forest-scene stage-${stage}`} viewBox="0 0 430 240" role="img" aria-label="Animated forest landscape with satellite scanning and vegetation layers">
        <defs><linearGradient id="terrain" x2="1" y2="1"><stop stopColor="#183b29"/><stop offset="1" stopColor="#0a201c"/></linearGradient><linearGradient id="scan" x2="0" y2="1"><stop stopColor="#bcf4a0" stopOpacity="0"/><stop offset="1" stopColor="#bcf4a0" stopOpacity=".6"/></linearGradient><pattern id="scenegrid" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M24 0H0V24" fill="none" stroke="#86b58b" strokeWidth=".5" opacity=".22"/></pattern><g id="pine"><path d="m0-13-8 12h4l-8 11h24L4-1h4L0-13Z" fill="#77b176"/><path d="M0 8v8" stroke="#a2c99a" strokeWidth="2"/></g></defs>
        <rect width="430" height="240" rx="8" fill="url(#terrain)"/>
        <path d="M-10 75C45 35 102 140 161 101S258 12 320 46s98 16 131-10" fill="none" stroke="#305443" strokeWidth="54"/>
        <path d="M-10 75C45 35 102 140 161 101S258 12 320 46s98 16 131-10" fill="none" stroke="#68a9a0" strokeOpacity=".52" strokeWidth="15"/>
        <rect width="430" height="240" fill="url(#scenegrid)"/>
        {[[44,145],[80,180],[120,151],[162,199],[196,165],[243,199],[281,155],[326,181],[369,143],[399,197],[40,29],[110,31],[176,41],[225,27],[326,108],[374,81]].map(([x,y],i)=><use key={i} href="#pine" x={x} y={y} opacity={.55+(i%3)*.15}/>)}
        <path className="study-polygon" d="m93 51 133-24 108 80-51 109-137-21-69-81Z" fill={stage===1?'#91df6730':'#91df6708'} stroke="#d5e793" strokeWidth="1.8" strokeDasharray="6 4"/>
        <path className="change-patch" d="m255 131 37-15 21 24-15 36-34-12Z" fill={stage===2?'#e0bc6466':'transparent'} stroke={stage===2?'#e0bc64':'transparent'}/>
        <rect className="satellite-scan" x="0" y="0" width="430" height="55" fill="url(#scan)"/>
        <g className="satellite-icon" transform="translate(350 30)"><path d="m0 0 9 9-9 9-9-9Z" fill="#c1d8be"/><path d="m-24-8 10 10-10 10-10-10Zm46 20 10 10-10 10-10-10Z" fill="#8ba8a1" stroke="#b6d4b5"/><path d="m-14 2 7 5m14 6 9 5" stroke="#c1d8be" strokeWidth="2"/></g>
        <text x="15" y="222" fill="#c4d7c0" fontSize="9" fontFamily="monospace">43QFE · 10 m GRID</text><circle className="scene-pulse" cx="229" cy="128" r="5" fill="#c9eca3"/><circle className="scene-ring" cx="229" cy="128" r="18" fill="none" stroke="#c9eca3"/>
      </svg>
      <div className="scene-bottom"><ForestLogo size={26}/><div><strong>ForestGuard AI</strong><span>{['Read saved satellite observations','Mask clouds and uncertain pixels','Compare common usable coverage'][stage]}</span></div><i className="live-orb"/></div>
    </div>
    <div className="flow-connector"><span>{['Imagery acquired','Quality layer aligned','Comparison prepared'][stage]}</span></div>
    <div className="analysis-window"><div className="analysis-icon">✦</div><div><strong>{['A view from above.','A clearer signal.','Evidence to review.'][stage]}</strong><span>{['Blue · Green · Red · Near infrared','Usable pixels, consistent geographic grid','Inspect dates and vegetation indicators'][stage]}</span></div><div className="analysis-bars"><i/><i/><i/><i/><i/></div></div>
    <div className="motion-stages">{['Observe','Analyze','Compare'].map((text,i)=><div className={i===stage?'active':''} key={text}><i/><small>0{i+1}</small><span>{text}</span></div>)}</div>
    <p className="motion-caption">Satellite imagery → usable observations → local insights</p>
  </div>;
}

export default function Landing({onLogin}){
  const [stage,setStage]=useState(0),[paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches),[loginOpen,setLoginOpen]=useState(false),[password,setPassword]=useState('joga@123'),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const dialog=useRef(null);
  useEffect(()=>{if(paused)return;const id=setInterval(()=>setStage(s=>(s+1)%3),3600);return()=>clearInterval(id);},[paused]);
  useEffect(()=>{if(loginOpen)dialog.current.showModal();else dialog.current?.close();},[loginOpen]);
  useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('.landing .reveal').forEach(e=>observer.observe(e));return()=>observer.disconnect();},[]);
  function openLogin(){setError('');setLoginOpen(true);}
  async function signIn(event){event.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({district:'Harda',beat:'Joga',password})});const result=await response.json();if(!response.ok)throw Error(result.detail||'Could not sign in');setLoginOpen(false);onLogin(result);}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <div className="landing" id="home"><a className="skip-link" href="#landing-main">Skip to content</a>
    <header className="landing-nav"><a href="#home" className="landing-brand"><ForestLogo/><span>ForestGuard<small>Intelligence for a greener tomorrow</small></span></a><nav aria-label="Landing navigation"><a href="#about">About</a><a href="#workflow">How it works</a><a href="#access">Officer access</a><a href="#faq">FAQ</a></nav><button className="land-button" onClick={openLogin}>Officer login <span>↗</span></button></header>
    <main id="landing-main" className="landing-main"><section className="landing-hero"><div className="hero-copy"><div className="hero-intro">Our forests. Our future. Our responsibility.</div><p className="hero-aside">A clearer view from above. A better decision on the ground.</p><h1>Keep it <span key={stage} className="cycling-word">{['Green.','Protected.','Thriving.'][stage]}</span><br/><span className="lime-line">See the change.</span><br/><span className="mint-line">Guard the future.</span></h1><p className="hero-description">Turn satellite observations into a clearer picture of your forest. Explore the landscape, compare dates, and bring the evidence back to the officers who know it best.</p><div className="hero-actions"><button className="land-button" onClick={openLogin}>Explore Joga beat <span>↗</span></button><a className="land-button outline" href="#workflow">See how it works <span>↓</span></a></div><div className="hero-tags"><span><i/> Joga · Harda, Madhya Pradesh</span><span>Built for local operation</span></div></div><ForestAnimation stage={stage} paused={paused} onPause={()=>setPaused(!paused)}/></section>
    <section id="about" className="landing-section reveal"><div className="section-eyebrow">WHY FORESTGUARD?</div><h2>Every forest has a story.<br/><span>See what the landscape is telling you.</span></h2><p className="section-description">Bring observations, dates and geographic context together. Less time searching through files. More time understanding what needs a closer look.</p><div className="feature-grid">{[['01','Observe your landscape','Inspect saved Sentinel-2 imagery on its original 10 m grid. See acquisition dates, quality masks and the pixels available for analysis.','◈'],['02','Compare the evidence','Put two aligned observations side by side. Pan and zoom together, inspect common coverage and calculate vegetation indicators.','⌁'],['03','Keep the work with you','Maps, checks and reports stay on your computer. Open saved observations without an online basemap or paid model service.','♧']].map(([n,title,text,icon])=><article key={n}><div className="feature-number">{n}<span>{icon}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="workflow" className="landing-section workflow-section reveal"><div className="section-eyebrow">HOW FORESTGUARD WORKS</div><h2>Observe. Understand. <span>Act.</span></h2><p className="section-description">A traceable path from a satellite observation to a report you can review.</p><div className="workflow-track">{[['Access your beat','Sign in to the Harda district workspace and select Joga beat. The pilot observations are already loaded.'],['Inspect the observation','View true-colour imagery with acquisition dates, band order and geographic grid information.'],['Check the signal','Run stored-data integrity checks and calculate the near-infrared vegetation indicator from saved bands.'],['Compare the dates','Explore aligned observations and their common usable coverage. Review visual differences in context.'],['Take the evidence','Download CSV or HTML reports with dates, coverage and provenance for further review.']].map(([title,text],i)=><article key={title}><div className="workflow-orbit"><span>STAGE</span><strong>0{i+1}</strong></div><div><small>STEP 0{i+1}</small><h3>{title}</h3><p>{text}</p></div></article>)}</div><div className="workflow-result"><span>THE RESULT</span> Better observations. More informed forest decisions. <button onClick={openLogin}>Open the workspace ↗</button></div></section>
    <section id="access" className="landing-section access-section reveal"><div><div className="section-eyebrow">THE JOGA PILOT</div><h2>Your forest.<br/><span>Your workspace.</span></h2><p className="section-description">A dedicated local workspace for the Joga pilot in Harda district, Madhya Pradesh. Saved observations are ready to explore.</p><button className="land-button" onClick={openLogin}>Login to officer workspace <span>↗</span></button></div><div className="access-card"><ForestLogo size={65}/><div className="access-label">FOREST OFFICER ACCESS</div><h3>Joga beat</h3><p>Harda district · Madhya Pradesh</p><dl><dt>Satellite source</dt><dd>Sentinel-2 L2A</dd><dt>Saved observations</dt><dd>March 2024 & March 2025</dd><dt>Workspace</dt><dd><i/> Local & ready</dd></dl><button className="land-button outline" onClick={openLogin}>Enter workspace →</button></div></section>
    <section id="faq" className="landing-section faq-section reveal"><div><div className="section-eyebrow">COMMON QUESTIONS</div><h2>Got a question?</h2><p className="section-description">A quick look at the current pilot.</p></div><div className="faq-items">{[['What can I do in the workspace?','Explore saved imagery, compare dates, inspect coverage masks, run file checks, calculate NDVI vegetation indicators and export reports.'],['Does it work without the Internet?','The application, maps and saved-data analysis run on this computer. Internet is needed only when acquiring fresh imagery or installing dependencies.'],['What does the vegetation indicator show?','NDVI measures the relative near-infrared and red reflectance signal. Green crops and scrub can also have high NDVI; it is not a forest classification or a diagnosis of forest loss.'],['Is the whole Joga beat mapped?','The current real-data observation uses a sourced candidate compartment outline for pipeline checks. It is not a confirmed current full-beat boundary.'],['Are demonstration outputs identified?','Yes. Generated class layers use the Synthetic demo label. The animated hero is a workflow illustration, while the officer workspace displays measured saved-data results.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
    <section className="landing-final reveal"><ForestLogo size={48}/><h2>See more. <span>Protect better.</span></h2><p>Start with the evidence. Bring your forest into focus.</p><button className="land-button" onClick={openLogin}>Explore ForestGuard AI ↗</button></section>
    </main><footer className="landing-footer"><div><a href="#home" className="landing-brand"><ForestLogo size={36}/><span>ForestGuard<small>Intelligence for a greener tomorrow</small></span></a><p>Observe the landscape.<br/>Guard what matters.</p></div><div><strong>EXPLORE</strong><a href="#about">About ForestGuard</a><a href="#workflow">How it works</a></div><div><strong>THE PILOT</strong><a href="#access">Joga · Harda</a><button onClick={openLogin}>Officer login</button></div><div><strong>THE PROJECT</strong><p>Local forest observation workspace<br/>© 2026 ForestGuard AI</p><a href="#faq">Questions & data context</a></div></footer>
    <dialog ref={dialog} className="officer-dialog" onCancel={()=>setLoginOpen(false)}><button className="dialog-close" aria-label="Close login" onClick={()=>setLoginOpen(false)}>×</button><ForestLogo size={50}/><div className="section-eyebrow">FOREST OFFICER WORKSPACE</div><h2>Welcome back.</h2><p>Your landscape, ready to explore.</p><form onSubmit={signIn}><label>District<select aria-label="District" defaultValue="Harda"><option>Harda</option></select></label><label>Forest beat<select aria-label="Forest beat" defaultValue="Joga"><option>Joga</option></select></label><label>Password<div className="password-field"><input aria-label="Password" type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/><button type="button" onClick={()=>setShowPassword(!showPassword)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?'Hide':'Show'}</button></div></label><small className="login-hint">Local pilot access · default password: joga@123</small>{error&&<p role="alert" className="login-error">{error}</p>}<button className="land-button" disabled={busy} type="submit">{busy?'Opening your workspace…':'Login to Joga workspace'} <span>→</span></button></form><span className="login-footnote">Harda district · Joga beat · Local session</span></dialog>
  </div>;
}
