import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import './style.css';
import Landing, {ForestLogo} from './Landing';
import ChangeWorkspace from './ChangeWorkspace';
import ResearchWorkspace from './ResearchWorkspace';
import ResearchChangeWorkspace from './ResearchChangeWorkspace';
import {startForestCursor} from './landingEffects';

const paths={leaf:'M12 21c-7-3-8-12 6-17 3 12-2 17-6 17Zm0 0c-2-5 0-9 4-13',grid:'M3 3h7v7H3zm11 0h7v7h-7zM3 14h7v7H3zm11 0h7v7h-7z',map:'m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3zm6-3v15m6-12v15',database:'M20 6c0 2-4 3-8 3S4 8 4 6s4-3 8-3 8 1 8 3ZM4 6v12c0 2 4 3 8 3s8-1 8-3V6M4 12c0 2 4 3 8 3s8-1 8-3',file:'M14 3H5v18h14V8zm0 0v5h5M8 12h8M8 16h6',arrow:'M5 12h14m-5-5 5 5-5 5',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',upload:'M12 16V4m-5 5 5-5 5 5M4 17v4h16v-4',check:'m5 12 4 4 10-10',search:'M10 18a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm6-2 6 6',focus:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5M12 8v8m-4-4h8',layers:'m12 3 10 6-10 6L2 9Zm-9 11 9 6 9-6',clock:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-15v6l4 2'};
function Icon({name,size=20}) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.leaf}/></svg>; }
const percent=n=>`${((n||0)*100).toFixed(2)}%`;
const number=n=>Number(n||0).toLocaleString('en-IN');
const dateLabel=d=>new Date(d+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
async function api(url,options) { const response=await fetch(url,options); if(!response.headers.get('content-type')?.includes('application/json')) throw Error('The local ForestGuard API did not return JSON. Check that the local server is running.'); const result=await response.json(); if(response.status===401) window.dispatchEvent(new Event('forestguard-session-expired')); if(!response.ok) throw Error(result.detail||'Request failed'); return result; }

function MapPane({data,observation,layer,rings,fitSignal,index,maps,busy}) {
  const host=useRef(null),map=useRef(null),image=useRef(null),outline=useRef(null),fitted=useRef('');
  useEffect(()=>{
    const instance=L.map(host.current,{crs:L.CRS.Simple,minZoom:-2,maxZoom:5,zoomControl:false,attributionControl:false});
    L.control.zoom({position:'topleft'}).addTo(instance); map.current=instance; maps.current[index]=instance;
    instance.on('move',()=>{const peer=maps.current[1-index]; if(peer&&!busy.current){busy.current=true;peer.setView(instance.getCenter(),instance.getZoom(),{animate:false});busy.current=false;}});
    const resize=new ResizeObserver(()=>instance.invalidateSize());resize.observe(host.current);
    return ()=>{resize.disconnect();instance.off("move");maps.current[index]=null;instance.remove();map.current=null;};
  },[]);
  useEffect(()=>{
    if(!map.current||!data||!observation)return;
    const bounds=[[0,0],[data.height,data.width]];
    image.current?.remove();
    image.current=L.imageOverlay(`/api/datasets/${data.id}/${observation.id}/image/${layer}`,bounds).addTo(map.current);
    if(fitted.current!==data.id){map.current.fitBounds(bounds,{padding:[22,22]});fitted.current=data.id;}
    outline.current?.remove();
    outline.current=L.layerGroup(rings.map(ring=>L.polyline(ring.map(([x,y])=>[data.height-y,x]),{color:'#f3db82',weight:1.5,opacity:.95}))).addTo(map.current);
  },[data?.id,observation?.id,layer,rings]);
  useEffect(()=>{if(map.current&&data)map.current.fitBounds([[0,0],[data.height,data.width]],{padding:[22,22]});},[fitSignal]);
  return <div className="map-pane"><div ref={host} className="leaflet-host" role="img" aria-label={`${data.title}, ${observation.name}, ${layer} layer`}/><div className="map-date"><span className="map-dot"/>{dateLabel(observation.date)}{data.kind==='synthetic'&&<small>Simulated · {observation.name}</small>}</div><div className="map-scale">{data.resolution} m / pixel <span>Saved raster</span></div></div>;
}

function MonthlyReports(){
  const [report,setReport]=useState(null),[range,setRange]=useState(60),[error,setError]=useState('');
  useEffect(()=>{api('/api/reports/monthly-demo').then(setReport).catch(e=>setError(e.message));},[]);
  if(error)return <div className="error-box" role="alert">{error}</div>;
  if(!report)return <div className="empty-state">Preparing the monthly report…</div>;
  const rows=report.months.slice(-range),first=rows[0],last=rows.at(-1),loss=first.simulated_canopy_ha-last.simulated_canopy_ha,fires=rows.reduce((s,r)=>s+r.simulated_fire_detections,0),max=Math.max(...rows.map(r=>r.simulated_fire_detections),1);
  const y=r=>155-(r.simulated_canopy_ha-100)*3.1,x=i=>35+i*850/Math.max(rows.length-1,1),points=rows.map((r,i)=>`${x(i)},${y(r)}`).join(' ');
  return <div className="monthly-report"><div className="sim-banner"><b>SIMULATED HISTORY · 60 MONTHS</b><span>Generated monthly values · no measured satellite history or recorded fires</span></div><div className="monthly-title"><div><div className="small-label">FOREST COVER & FIRE MONITORING</div><h2>Forest change, month by month.</h2><p>Simulated study area · {first.label} to {last.label}</p></div><a className="button secondary" href="/api/reports/monthly-demo.csv">Download monthly report ↓</a></div><div className="monthly-cards"><article><span>Simulated tree cover</span><strong>{first.simulated_canopy_ha} → {last.simulated_canopy_ha} ha</strong><small>{loss.toFixed(1)} ha change in simulated data</small></article><article><span>Possible fire signals</span><strong>{fires}</strong><small>Generated monthly signals · {range} months</small></article><article><span>Report period</span><strong>{range} months</strong><small>{first.label} — {last.label}</small></article></div><section className="panel history-panel"><div className="panel-heading"><div><h3>Simulated tree-cover trend</h3><span>Simulated forest area · hectares</span></div><div className="range-switch">{[[12,'1 year'],[60,'5 years']].map(([v,t])=><button className={range===v?'selected':''} key={v} onClick={()=>setRange(v)}>{t}</button>)}</div></div><svg className="history-chart" viewBox="0 0 920 190" role="img" aria-label="Simulated monthly tree-cover area"><title>Simulated values, not observations</title><path d="M35 20H885M35 88H885M35 155H885" stroke="#e9eee5"/><polyline points={points} fill="none" stroke="#397e51" strokeWidth="3"/>{rows.map((r,i)=><circle key={r.month} cx={x(i)} cy={y(r)} r="2.2" fill="#36794d"><title>{r.label}: simulated {r.simulated_canopy_ha} hectares</title></circle>)}</svg><div className="chart-caption"><span>{first.label}</span><span>{last.label}</span></div></section><section className="panel history-panel"><div className="panel-heading"><div><h3>Simulated fire detections by month</h3><span>Illustrative seasonal pattern · no actual fire records</span></div><Icon name="leaf"/></div><div className="fire-bars" role="img" aria-label="Simulated monthly fire signals">{rows.map(r=><i key={r.month} title={`${r.label}: ${r.simulated_fire_detections} simulated signals`} style={{height:`${8+r.simulated_fire_detections/max*100}%`}}/>)}</div><div className="chart-caption"><span>{first.label}</span><span>{fires} simulated signals</span><span>{last.label}</span></div><p className="risk-line">Simulated seasonal risk index: <strong>{last.simulated_fire_risk_pct}/100</strong> <span>No live fire or weather feed</span></p></section><p className="demo-footnote">Source: reproducibly generated synthetic history. This series does not represent observations or recorded fires in Joga.</p></div>;
}

function App({onLogout,hosted=false}){
  const [analysis,setAnalysis]=useState(null),[scenario,setScenario]=useState(false);
  const [datasets,setDatasets]=useState([]),[selected,setSelected]=useState('compartment-279'),[section,setSection]=useState('Overview'),[viewId,setViewId]=useState('1');
  const [layer,setLayer]=useState('imagery'),[compare,setCompare]=useState(false),[rings,setRings]=useState([]),[showBoundary,setShowBoundary]=useState(true),[menuOpen,setMenuOpen]=useState(false);
  const [activity,setActivity]=useState([]),[loading,setLoading]=useState(true),[checking,setChecking]=useState(false),[toast,setToast]=useState(''),[error,setError]=useState(''),[search,setSearch]=useState(''),[fit,setFit]=useState(0);
  const maps=useRef([]),syncBusy=useRef(false);
  const scopedDatasets=datasets.filter(d=>d.id===(scenario?'demo':'compartment-279'));
  const data=scopedDatasets.find(d=>d.id===selected)||scopedDatasets[0]; const observation=data?.views.find(v=>v.id===viewId)||data?.views[0];
  const isDemo=data?.kind==='synthetic'; const hasPair=!isDemo&&data?.views.length>1;
  async function refresh(){setDatasets((await api('/api/datasets')).filter(d=>['compartment-279','demo'].includes(d.id)));setActivity(await api('/api/activity'));}
  useEffect(()=>{refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{if(!data)return;let active=true;setViewId(data.views[0].id);setLayer('imagery');setCompare(false);setShowBoundary(true);setRings([]);api(`/api/datasets/${data.id}/outline`).then(r=>{if(active)setRings(r.rings);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[data?.id]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id);},[toast]);
  async function check(){setChecking(true);setError('');try{const r=await api(`/api/datasets/${data.id}/validate`,{method:'POST'});setToast(r.detail);setActivity(await api('/api/activity'));}catch(e){setError(e.message);}finally{setChecking(false);}}
  async function analyze(){if(!data)return;if(section==='Forest & fire'){setSection('Map workspace');return;}setChecking(true);setError('');try{const r=await api(`/api/datasets/${data.id}/analyze`,{method:'POST'});setAnalysis({...r,dataset:data.id});setSection('Overview');setLayer(data.layers.includes('ndvi')?'ndvi':'classes');setToast('Saved imagery analyzed');setActivity(await api('/api/activity'));}catch(e){setError(e.message);}finally{setChecking(false);}}
  useEffect(()=>{if(!data)return;let active=true;setAnalysis(null);api(`/api/datasets/${data.id}/analyze`,{method:'POST'}).then(r=>{if(active)setAnalysis({...r,dataset:data.id});}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[data?.id]);
  const sectionTitle={Overview:'Forest overview','Map workspace':'Satellite images','Research map':'Research map',Reports:'Reports','Forest & fire':'Monthly scenario','Change detection':'Change detection'}[section]||section;
  const visible=scopedDatasets.filter(d=>(d.title+' '+d.subtitle).toLowerCase().includes(search.toLowerCase()));
  const relevantActivity=activity.filter(a=>a.dataset===(scenario?'demo':'compartment-279'));
  const compareView=data?.views.find(v=>v.id!==observation?.id);
  return <div className="app-shell">
    <aside className="sidebar"><div className="officer-brand-row"><div className="brand"><div className="brand-mark"><ForestLogo size={30}/></div><div>ForestGuard<span>AI MONITORING WORKSPACE</span></div></div><button className="officer-menu-toggle" aria-controls="officer-navigation" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?'Close menu':'Menu'} <span aria-hidden="true">{menuOpen?'×':'☰'}</span></button></div>
      <div className="workspace-label">WORKSPACE</div><nav id="officer-navigation" aria-label="Officer workspace" className={menuOpen?'is-open':''}>{(scenario?[['Overview','grid'],['Map workspace','map'],['Change detection','layers'],['Forest & fire','leaf'],['Reports','file']]:[['Overview','grid'],['Map workspace','map'],['Research map','leaf'],['Estimated change','layers'],['Reports','file']]).map(([name,icon])=><button key={name} onClick={()=>{setSection(name);setMenuOpen(false);}} className={section===name?'active':''}><Icon name={icon}/><span>{name==='Overview'?'Forest overview':name==='Map workspace'?'Satellite images':name==='Forest & fire'?'Monthly scenario':name}</span>{section===name&&<i/>}</button>)}</nav>
      <div className="sidebar-note"><div className="status-dot"/> {hosted?'Hosted workspace':'Local workspace'}<p>Saved forest observations.<br/>{hosted?'Available on this website.':'Available on this computer.'}</p><span>Assigned forest area</span></div>
      <div className="sidebar-footer"><div className="avatar">FG</div><div>Project workspace<small>{hosted?'Hosted session':'Local session'}</small></div><Icon name="leaf" size={16}/></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> <strong>{sectionTitle}</strong></div><div className="topbar-right"><span className="local-badge"><i/> {hosted?'Hosted':'Local'}</span><span className="officer-label">Forest officer</span><button className="button secondary" onClick={onLogout}>Logout</button></div></header>
    <main><div className="data-mode-bar"><label>Data view<select aria-label="Data view" value={scenario?'synthetic':'observations'} onChange={e=>{const next=e.target.value==='synthetic';setScenario(next);setSelected(next?'demo':'compartment-279');setSection('Overview');setMenuOpen(false);setError('');}}><option value="observations">Saved observations · compartment 279</option><option value="synthetic">Synthetic scenario · fictional study area</option></select></label><span>{scenario?'Generated data for workflow testing':'Real dated images prepared by ForestGuard'}</span></div>{hosted&&<div className="hosting-note" role="note">ForestGuard prepares the saved images for your area. No upload is needed. Check image dates before making decisions; hosted activity history is temporary.</div>}<div className="page-heading"><div><div className="eyebrow">FORESTGUARD AI</div><h1>{sectionTitle}</h1><p>{section==='Change detection'?'Compare dated class maps, inspect usable coverage and export the evidence.':section==='Overview'?(scenario?'Synthetic scenario · generated images and known classes.':'Compartment 279 · saved satellite images and measured vegetation indicators.'):section==='Forest & fire'?'Generated monthly history for the synthetic scenario.':section==='Map workspace'?'View a saved satellite image and compare dates.':section==='Estimated change'?'Compare real December images and inspect estimated tree-cover transitions.':section==='Research map'?'Inspect our stored tree-cover proxy and download its evidence.':section==='Datasets'?'Your saved imagery and simulated inputs.':'Export traceable, shareable snapshots of your saved data.'}</p></div>{!['Change detection','Research map','Estimated change'].includes(section)&&<button className="button secondary" onClick={analyze} disabled={checking}><Icon name={checking?"clock":"layers"}/> {checking?"Analyzing saved images…":section==='Forest & fire'?'Open satellite map':'Analyze saved images'}</button>}</div>
    {error&&<div className="error-box" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}
    {section==='Change detection'?<ChangeWorkspace api={api} onRun={()=>api('/api/activity').then(setActivity).catch(e=>setError(e.message))}/>:section==='Estimated change'?<ResearchChangeWorkspace api={api}/>:section==='Research map'?<ResearchWorkspace api={api}/>:section==='Forest & fire'?<MonthlyReports/>:loading?<div className="empty-state">Opening saved forest records…</div>:!data?<div className="empty-state"><Icon name="database" size={38}/><h2>Your workspace is ready.</h2><p>ForestGuard observations for compartment 279 are unavailable. The project team must restore the prepared data.</p><button className="button primary" onClick={()=>{setLoading(true);setError('');refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Retry saved observations</button></div>:<>
      {(section==='Overview'||section==='Map workspace')&&<>
        <div className="dataset-bar"><div><span className={`data-badge ${isDemo?'demo':''}`}>{isDemo?'Simulated data':'Real imagery'}</span><select aria-label="Select dataset" value={data.id} onChange={e=>setSelected(e.target.value)}>{scopedDatasets.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></div><span className="dataset-scope">{data.scope}</span></div>
        {data.limits&&<div className="sim-banner"><b>SAVED OBSERVATIONS</b><span>Vegetation measurements from different seasons · forest-loss and fire findings are not available.</span></div>}
        {analysis?.dataset===data.id&&<section className="panel analysis-results"><div className="panel-heading"><div><h2>Greenness indicator</h2><span>Leaf-growth signal from {isDemo?"simulated inputs":"saved satellite images"}</span></div><Icon name="leaf"/></div><div className="analysis-observations">{analysis.observations.map(v=><article key={v.date}><small>{dateLabel(v.date)}</small><strong>{v.median_ndvi.toFixed(4)}</strong><span>Leaf-greenness signal · {number(v.valid_pixels)} clear pixels</span><p>{v.vegetation_signal_percent}% show stronger leaf-greenness signals</p></article>)}{analysis.median_ndvi_difference!==undefined&&<article><small>Between saved dates</small><strong>{analysis.median_ndvi_difference>0?"+":""}{analysis.median_ndvi_difference.toFixed(4)}</strong><span>Difference in median NDVI</span></article>}</div><p className="analysis-context">{analysis.interpretation}</p></section>}
        <div className="stats-grid"><Stat label={isDemo?'Known-label coverage':hasPair?'Common usable coverage':'Usable coverage'} value={percent(isDemo?observation.coverage:data.coverage)} note={isDemo?'Inside the selected simulated split':hasPair?'Valid observations across saved dates':'Valid pixels inside the stored study mask'} icon="check"/>
          <Stat label={isDemo?'Simulated tree cover':'Saved maps'} value={isDemo?`${observation.forest_ha.toFixed(2)} ha`:data.views.length} note={isDemo?'Generated class pixels, not a model result':'Acquisition dates available to inspect'} icon="leaf"/>
          <Stat label="Image detail" value={`${data.resolution} m`} note={`Each image square covers ${data.resolution} metres`} icon="focus"/>
          <Stat label="Saved image files" value={data.verified_files} note="Run a fresh check below" icon="file"/></div>
        <div className={`workspace-grid ${section==='Map workspace'?'expanded':''}`}><section className="panel map-panel"><div className="panel-heading"><div><h2>Observation explorer</h2><span>Pan, zoom and compare stored layers</span></div><button className="icon-button" title="Fit image" aria-label="Fit image" onClick={()=>setFit(fit+1)}><Icon name="focus"/></button></div>
          <div className="map-toolbar"><div className="segments">{data.layers.map(l=><button key={l} className={layer===l?'chosen':''} onClick={()=>setLayer(l)}>{l==='imagery'?'True colour':l==='classes'?'Simulated tree cover':l==='ndvi'?'Vegetation signal':data.common_mask?'Common clear pixels':'Clear pixels'}</button>)}</div><label className="compare-toggle"><input type="checkbox" checked={compare} disabled={data.views.length<2} onChange={e=>setCompare(e.target.checked)}/>Compare</label></div>
          <div className={`maps ${compare?'dual':''}`}><MapPane key={data.id+'-main'} data={data} observation={observation} layer={layer} rings={showBoundary?rings:[]} fitSignal={fit} index={0} maps={maps} busy={syncBusy}/>{compare&&compareView&&<MapPane key={data.id+'-compare'} data={data} observation={compareView} layer={layer} rings={showBoundary?rings:[]} fitSignal={fit} index={1} maps={maps} busy={syncBusy}/>}</div>
          <div className="map-footer"><label><input type="checkbox" checked={showBoundary} onChange={e=>setShowBoundary(e.target.checked)}/><span className="legend-outline"/>{isDemo?'Fictional study grid':data.id==='compartment-279'?'Selected compartment 279 polygon':data.id==='sentinel'?'Candidate outline':'Outline'}</label><a href={`/api/datasets/${data.id}/report/html`}>Download report ↗</a></div>
          <div className="date-strip">{data.views.map(v=><button key={v.id} className={observation.id===v.id?'selected':''} onClick={()=>setViewId(v.id)}><span>{isDemo?v.name:dateLabel(v.date)}</span><small>{isDemo?'Simulated '+dateLabel(v.date):'Satellite image · leaf-growth signals'}</small></button>)}</div>
        </section><aside className="insight-stack"><section className="panel insight-card"><div className="panel-heading"><h2>Observation details</h2><Icon name="layers"/></div><dl><dt>{isDemo?'Simulated date':'Date collected'}</dt><dd>{dateLabel(observation.date)}</dd><dt>Map location</dt><dd>{isDemo?'Fictional study area':'Harda region'}</dd><dt>Image contents</dt><dd>{'Natural colours and leaf-growth signals'}</dd><dt>Data version</dt><dd className="mono">{data.version}</dd></dl><button className="button primary full" onClick={check} disabled={checking}><Icon name={checking?'clock':'check'}/>{checking?'Checking stored files…':'Check saved image'}</button></section>
          <section className="panel insight-card"><div className="small-label">{isDemo?'SIMULATED DATA':'COVERAGE BY DATE'}</div><h3>{isDemo?'A safe place to test.':'Know what is observable.'}</h3><p>{isDemo?'These values are generated and do not represent any real forest.':hasPair?'Only pixels valid on both dates belong to the common coverage mask.':'The usable mask identifies observable pixels in this saved crop.'}</p>{data.views.map(v=><div className="coverage-row" key={v.id}><div><span>{isDemo?v.name:dateLabel(v.date)}</span><strong>{percent(v.coverage)}</strong></div><div className="bar"><i style={{width:percent(v.coverage)}}/></div></div>)}<div className="legend"><span><i className="green"/>{layer==='classes'?'Simulated forest':'Usable pixels'}</span>{layer==='classes'&&<span><i className="sand"/>Simulated non-forest</span>}</div></section>
          <section className="export-card"><Icon name="file" size={24}/><h3>Keep the evidence.</h3><p>Download dates, coverage and data provenance in a portable report.</p><a href={`/api/datasets/${data.id}/report/html`} onClick={()=>setTimeout(()=>api('/api/activity').then(setActivity),700)}>Export report <Icon name="arrow" size={17}/></a></section></aside></div>
      </>}
      {section==='Datasets'&&<><div className="library-toolbar"><div className="search-box"><Icon name="search"/><input aria-label="Search datasets" placeholder="Search your datasets…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span>{visible.length} saved datasets</span></div><div className="dataset-cards">{visible.map(d=><article className="panel library-card" key={d.id}><div className="dataset-thumb" style={{backgroundImage:`url(/api/datasets/${d.id}/${d.views[0].id}/image/imagery)`}}><span className={`data-badge ${d.kind==='synthetic'?'demo':''}`}>{d.kind==='synthetic'?'Simulated data':'Real imagery'}</span></div><div><h2>{d.title}</h2><p>{d.subtitle}</p><dl><dt>Observations</dt><dd>{d.views.length}</dd><dt>Resolution</dt><dd>{d.resolution} m</dd><dt>Scope</dt><dd>{d.scope}</dd></dl><button className="button secondary full" onClick={()=>{setSelected(d.id);setSection('Map workspace');}}>Open workspace <Icon name="arrow" size={17}/></button></div></article>)}</div>{visible.length===0&&<p className="empty-state">No datasets match your search.</p>}</>}
      {section==='Reports'&&<section className="panel report-panel"><div className="panel-heading"><div><h2>Reports, ready to travel.</h2><span>Dated images, measured coverage and vegetation evidence prepared by ForestGuard.</span></div><Icon name="download"/></div>{scopedDatasets.map(d=><div className="report-row" key={d.id}><div className="report-icon"><Icon name="file"/></div><div><h3>{d.title}</h3><p>{d.views.length} observations · {d.kind==='synthetic'?'Simulated dates':'Acquisition dates'} · {d.resolution} m</p></div><a className="button secondary" href={`/api/datasets/${d.id}/report/csv`}>CSV <Icon name="download" size={16}/></a><a className="button primary" href={`/api/datasets/${d.id}/report/html`}>HTML report <Icon name="download" size={16}/></a></div>)}</section>}
      <><section className="panel activity-panel"><div className="panel-heading"><div><h2>Recent activity</h2><span>Checks and exports performed in this workspace</span></div><Icon name="clock"/></div>{relevantActivity.length?relevantActivity.slice(0,5).map(a=><div className="activity-row" key={a.id}><span className={`activity-status ${a.status}`}><Icon name="check" size={16}/></span><div><strong>{a.action}</strong><span>{a.detail}</span></div><time>{new Date(a.at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})}</time><span className="result-badge">{a.status}</span></div>):<div className="activity-empty">No checks yet. Run “Check dataset” to record a verified result.</div>}</section>
      </><footer className="page-footer"><span>ForestGuard AI · {isDemo?'Synthetic scenario':'Compartment 279 observation workspace'}</span><span>{data.attribution}</span></footer>
    </>}
    </main></div>{toast&&<div className="toast" role="status"><Icon name="check"/>{toast}</div>}
  </div>;
}
function Stat({label,value,note,icon}){return <article className="stat-card"><div className="stat-top"><span>{label}</span><Icon name={icon}/></div><strong>{value}</strong><small>{note}</small></article>;}
function ForestGuard(){
  const [officer,setOfficer]=useState(null),cursor=useRef(null);
  useEffect(()=>startForestCursor(cursor.current),[]);
  useEffect(()=>{const expired=()=>setOfficer(null);window.addEventListener('forestguard-session-expired',expired);api('/api/session').then(result=>{if(result.authenticated)setOfficer(result);}).catch(()=>{});return()=>window.removeEventListener('forestguard-session-expired',expired);},[]);
  async function logout(){await api('/api/logout',{method:'POST'});window.location.reload();}
  return <><div ref={cursor} className="motion-cursor site-cursor page-cursor" aria-hidden="true"><div className="site-cursor-pill"/></div>{officer?<App onLogout={logout} hosted={officer.hosting==='vercel'}/>:<Landing onLogin={result=>{setOfficer(result);window.scrollTo(0,0);}}/>}</>;
}
createRoot(document.getElementById('root')).render(<ForestGuard/>);
