import React,{useEffect,useState} from 'react';

export default function ResearchChangeWorkspace({api}){
  const [report,setReport]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[layer,setLayer]=useState('changes'),[revision,setRevision]=useState(0);
  async function refresh(){setBusy(true);setError('');try{setReport(await api('/api/research/change'));setRevision(n=>n+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{refresh();},[]);
  return <section aria-label="Estimated tree-cover change">
    <div className="sim-banner"><b>REAL IMAGES · RESEARCH ESTIMATE</b><span>Changes in predicted tree cover. Independent forest accuracy has not been established.</span></div>
    <div className="change-intro"><div><h2>See what changed. Inspect the images.</h2><p>Compartment 279 · December observations one year apart · common clear coverage only.</p></div><button className="button secondary" disabled={busy} onClick={refresh}>{busy?'Checking evidence…':'Refresh saved comparison'}</button></div>
    {error&&<p className="error-box" role="alert">{error}</p>}
    {!report?<p role="status">{busy?'Opening saved comparison…':'Comparison unavailable.'}</p>:!report.available?<p>{report.detail}</p>:<>
      <div className="change-period">{report.observations.map(item=><span key={item.date}>Image date: <strong>{item.date}</strong></span>)}</div>
      <div className="stats-grid">{[['Suspected tree-cover loss',`${report.transition_area_ha['2'].toFixed(2)} ha`,'Model estimate'],['Suspected tree-cover gain',`${report.transition_area_ha['3'].toFixed(2)} ha`,'Model estimate'],['Common clear coverage',`${(report.common_usable_fraction*100).toFixed(2)}%`,'Coverage, not accuracy'],['Observable area',`${report.common_observable_area_ha.toFixed(2)} ha`,'Excluded pixels receive no change class']].map(([title,value,note])=><article className="stat-card" key={title}><div className="stat-top">{title}</div><strong>{value}</strong><small>{note}</small></article>)}</div>
      <div className="change-tools"><label>Evidence layer <select aria-label="Evidence layer" value={layer} onChange={e=>{setLayer(e.target.value);setError('');}}><option value="changes">Estimated change map</option><option value="before">Satellite image · {report.observations[0].date}</option><option value="after">Satellite image · {report.observations[1].date}</option></select></label><span>20 m analysis grid · stored images</span></div>
      <section className="panel" style={{padding:'1rem'}}><img style={{display:'block',width:'100%',maxHeight:'65vh',objectFit:'contain',background:'#173b2d'}} src={`/api/research/change/image/${layer}?v=${revision}`} alt={layer==='changes'?'Estimated tree-cover changes inside compartment 279':`Satellite observation ${report.observations[layer==='before'?0:1].date}`} onError={()=>setError('Evidence image could not be loaded. Refresh the saved comparison.')}/></section>
      <div className="change-legend">{[['#ef634b','Suspected loss'],['#54cfb4','Suspected gain'],['#287d4d','Stable tree cover'],['#a18a62','Stable other cover']].map(([color,text])=><span key={text}><i style={{background:color}}/>{text}</span>)}</div>
      <section className="panel change-evidence"><h3>How this estimate was calculated</h3><p>The same model classified both dated images. Tree-to-other predictions indicate suspected loss; other-to-tree predictions indicate suspected gain. Clouded or missing pixels are excluded. Each mapped pixel represents 0.04 ha.</p><p>{report.limits}</p><dl><dt>Model version</dt><dd>{report.model_version}</dd><dt>Common clear pixels</dt><dd>{report.common_observable_pixels.toLocaleString()} / {report.study_mask_pixels.toLocaleString()}</dd><dt>Source attribution</dt><dd>{report.observations.map(item=>item.attribution).join('; ')}</dd></dl><div className="change-actions">{[['csv','Change CSV'],['html','Offline image report'],['json','Evidence JSON'],['classes','Change GeoTIFF'],['before','Before classes'],['after','After classes']].map(([format,text])=><a key={format} className="button secondary" href={`/api/research/change/download/${format}`}>{text} ↓</a>)}</div></section>
    </>}
  </section>;
}
